<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-DJ4FDME" failures="1" tests="1" name="Test(failed)(failed)" time="0.141" errors="0" timestamp="2023-12-04T22:26:35 IST">
  <testcase classname="learnTestNG.TestScenario1" name="first_testcase" time="0.044">
    <failure type="java.lang.AssertionError" message="expected [Hello1] but found [Hello]">
      <![CDATA[java.lang.AssertionError: expected [Hello1] but found [Hello]
at learnTestNG.TestScenario1.first_testcase(TestScenario1.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="forth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- forth_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="learnTestNG.TestScenario1" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
</testsuite> <!-- Test(failed)(failed) -->
